import React from 'react'

const ProductRow = [
  {
    id: 1,
    title: "Beige Formal Chinos Pants",
    price: "$180",
    category: "Top Sale's",
    img: "/public/images/products/p1.jpg", 
  },
  {
    id: 2,
    title: "White Knife-Pleat Shirt",
    price: "$250",
    category: "Top Sale's",
    img: "/public/images/products/p2.jpg",
  },
  {
    id: 3,
    title: "Cream Color Shacket",
    price: "$100",
    category: "Top Sale's",
    img: "/public/images/products/p3.jpg",
  },
  {
    id: 4,
    title: "Café Racer Jacket",
    price: "$320",
    category: "Top Sale's",
    img: "/public/images/products/p4.jpg",
  },
  {
    id: 5,
    title: " Black Blouson Jacket",
    price: "$400",
    category: "Top Sale's",
    img: "/public/images/products/p5.jpg",
  },
  {
    id: 6,
    title: "Crop Top",
    price: "$220",
    category: "Summer",
    img: "/public/images/products/p6.jpg",
  },
  {
    id: 7,
    title: "Black Cargo Pants",
    price: "$150",
    category: "Summer",
    img: "/public/images/products/p7.jpg",
  },
  {
    id: 8,
    title: "Baggy White Pants",
    price: "$130",
    category: "Summer",
    img: "/public/images/products/p8.jpg",
  },
  {
    id: 9,
    title: "Wool Blend Overcoat",
    price: "$320",
    category: "Winter",
    img: "/public/images/products/p9.jpg",
  },
  {
    id: 10,
    title: "Woolen Sweater",
    price: "$150",
    category: "Winter",
    img: "/public/images/products/p10.jpg",
  },
  {
    id: 11,
    title: "Spidey Knit Beanie", 
    price: "$40",
    category: "Winter",
    img: "/public/images/products/p11.jpg",
  },
  {
    id: 12,
    title: "Leather Gloves",
    price: "$60",
    category: "Winter",
    img: "/public/images/products/p12.jpg",
  },
  {
    id: 13,
    title: "Graphic T-Shirt",
    price: "$35",
    category: "Trending",
    img: "/public/images/products/p13.jpg",
  },
  {
    id: 14,
    title: "Track Pants", 
    price: "$80",
    category: "Trending",
    img: "/public/images/products/p14.jpg",
  },
  {
    id: 15,
    title: "Casual Hoodie",
    price: "$70",
    category: "Trending",
    img: "/public/images/products/p15.jpg",
  },
  {
    id: 16,
    title: "Denim Shirt",
    price: "$190",
    category: "Trending",
    img: "/public/images/products/p16.jpg",
  },
  {
    id: 17,
    title: "Polo Shirt",
    price: "$210",
    category: "Trending",
    img: "/public/images/products/p17.jpg",
  },
  {
    id: 18,
    title: "High Top Sneakers",
    price: "$195",
    category: "Trending",
    img: "/public/images/products/p18.jpg",
  },
];

export default ProductRow
